log:
  level: error
  as-json: false

server:
  port: 3001

mongodb:
  subscription: 
    server: localhost
    database: xxx
  account:
    server: localhost
    database: xxx

services:
  web-internal:
    url: "http://xxx"
